name: name
ns: ns
deployment:
  container:
    name: test
    image: test-image
    ports:
      - name: http
        containerPort: 80
      - name: monitor
        containerPort: 9010
    resources:
      cpu:
        requests: 10
        limits: 100
      memory:
        requests: 20
        limits: 200
service:
  enabled: true
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: monitor
      port: 9010
      protocol: TCP
      targetPort: 9010
    - name: managing
      port: 9011
      protocol: TCP
      targetPort: 9011

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  port: 80
  path: /
  hostname: app.domain.com
